import React from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faHome,
  faBriefcase,
  faUser,
  faCog,
  faBoxes,
  faCubes,
  faListAlt,
  faTasks,
  faHistory,
  faExchangeAlt,
} from '@fortawesome/free-solid-svg-icons';

export const Routes = [
  {
    title: 'HOME',
    slug: 'home',
    path: '/',
    icon: <FontAwesomeIcon icon={faHome} className="anticon" />,
    roles: ['*'],
    childs: [],
    optionalIcon: true,
  },

  {
    title: 'AGF Workstation',
    slug: 'agf-workstation',
    path: '/agf-workstation',
    icon: <FontAwesomeIcon icon={faBriefcase} className="anticon" />,
    roles: ['*'],
    childs: [],
    optionalIcon: true,
  },
  {
    title: 'Items',
    slug: 'items',
    path: '/items',
    icon: <FontAwesomeIcon icon={faBoxes} className="anticon" />,
    roles: ['admin', 'staff'],
    childs: [],
    optionalIcon: true,
  },
  {
    title: 'Stocks',
    slug: 'stocks',
    path: '/stocks',
    icon: <FontAwesomeIcon icon={faCubes} className="anticon" />,
    roles: ['admin', 'staff'],
    childs: [],
    optionalIcon: true,
  },
  {
    title: 'Orders',
    slug: 'orders',
    path: '/orders',
    icon: <FontAwesomeIcon icon={faListAlt} className="anticon" />,
    roles: ['admin', 'staff'],
    childs: [],
    optionalIcon: true,
  },
  {
    title: 'Cycle Count',
    slug: 'recalculation',
    path: '/recalculation',
    icon: <FontAwesomeIcon icon={faBriefcase} className="anticon" />,
    roles: ['*'],
    childs: [],
    optionalIcon: true,
  },
  {
    title: 'AGF Queue',
    slug: 'agf-queue',
    path: '/agf-queue',
    icon: <FontAwesomeIcon icon={faTasks} className="anticon" />,
    roles: ['admin'],
    childs: [],
    optionalIcon: true,
  },
  {
    title: 'Transactions',
    slug: 'transactions',
    path: '/transactions',
    icon: <FontAwesomeIcon icon={faExchangeAlt} className="anticon" />,
    roles: ['admin', 'staff'],
    childs: [],
    optionalIcon: true,
  },
  {
    title: 'Logs',
    slug: 'logs',
    path: '/call-logs',
    icon: <FontAwesomeIcon icon={faHistory} className="anticon" />,
    roles: ['admin'],
    childs: [],
    optionalIcon: true,
  },
  {
    title: 'Users',
    slug: 'users',
    path: '/users',
    icon: <FontAwesomeIcon icon={faUser} className="anticon" />,
    roles: ['admin'],
    childs: [],
    optionalIcon: true,
  },
  {
    title: 'Configurations',
    slug: 'configurations',
    path: '/configurations',
    icon: <FontAwesomeIcon icon={faCog} className="anticon" />,
    roles: ['admin', 'staff'],
    childs: [],
    optionalIcon: true,
  },
];
