const users = require('./users/users.service.js');
const apiKeys = require('./api-keys/api-keys.service.js');
const roles = require('./roles/roles.service.js');
const forgot = require('./forgot/forgot.service.js');
const verify = require('./verify/verify.service.js');
const mail = require('./mail/mail.service.js');
const emailLogs = require('./email-logs/email-logs.service.js');
const multimedia = require('./multimedia/multimedia.service.js');
const labels = require('./labels/labels.service.js');
const menus = require('./menus/menus.service.js');
const version = require('./version/version.service.js');
const configs = require('./configs/configs.service.js');
const utils = require('./utils/utils.service.js');
const valid = require('./valid/valid.service.js');
const importCsv = require('./import-csv/import-csv.service.js');
const importLogs = require('./import-logs/import-logs.service.js');
const blacklist = require('./blacklist/blacklist.service.js');
const stocks = require('./stocks/stocks.service.js');
const items = require('./items/items.service.js');
const agfs = require('./agfs/agfs.service.js');
const orders = require('./orders/orders.service.js');
const wmsLogs = require('./wms-logs/wms-logs.service.js');
const pickupZones = require('./pickup-zones/pickup-zones.service.js');
const scanPallet = require('./scan-pallet/scan-pallet.service.js');
const palletReady = require('./pallet-ready/pallet-ready.service.js');
const agfTasks = require('./agf-tasks/agf-tasks.service.js');
const agvTasks = require('./agv-tasks/agv-tasks.service.js');
const agvs = require('./agvs/agvs.service.js');
const agvReady = require('./agv-ready/agv-ready.service.js');
const relocationReady = require('./relocation-ready/relocation-ready.service.js');
const stockReport = require('./stock-report/stock-report.service.js');
const transactions = require('./transactions/transactions.service.js');
const transactionReport = require('./transaction-report/transaction-report.service.js');
const connections = require('./connections/connections.service.js');
const exportCollections = require('./export-collections/export-collections.service.js');
const resendCalls = require('./resend-calls/resend-calls.service.js');
const services = require('./services/services.service.js');
const recalculation = require('./recalculation/recalculation.service.js');
// eslint-disable-next-line no-unused-vars
module.exports = function (app) {
  app.configure(users);
  app.configure(apiKeys);
  app.configure(roles);
  app.configure(forgot);
  app.configure(verify);
  app.configure(mail);
  app.configure(emailLogs);
  app.configure(multimedia);
  app.configure(labels);
  app.configure(menus);
  app.configure(version);
  app.configure(configs);
  app.configure(utils);
  app.configure(valid);
  app.configure(importCsv);
  app.configure(importLogs);
  app.configure(blacklist);
  app.configure(stocks);
  app.configure(items);
  app.configure(agfs);
  app.configure(orders);
  app.configure(wmsLogs);
  app.configure(pickupZones);
  app.configure(scanPallet);
  app.configure(palletReady);
  app.configure(agfTasks);
  app.configure(agvTasks);
  app.configure(agvs);
  app.configure(agvReady);
  app.configure(relocationReady);
  app.configure(stockReport);
  app.configure(transactions);
  app.configure(transactionReport);
  app.configure(connections);
  app.configure(exportCollections);
  app.configure(resendCalls);
  app.configure(services);
  app.configure(recalculation);
};
